# Generated by Django 5.1 on 2025-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
