# Generated by Django 5.1 on 2025-03-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_last_name_alter_author_pseudonym'),
    ]

    operations = [
    ]
